/*************************************************************************************
 * 
 * Author: Nibras Ahamed Reeza (CB004641)
 * Email: nibras.me@facebook.com
 * 
 * Created: 21st of December, 2013
 * 
 * This file part of the image processing artifact created for Imaging and Special
 * Effects module.
 * 
 * This file represents the main application. This mainly initializes the GUI components
 * which and then delegates calls to ImageWindow. It also handles taking user input for
 * various functions. Mostly code generated by Eclipse WindowBuilder. Logic for user 
 * input handle is towards the end of this file.
 * 
 * References:
 * 
 * Complete list is given at the end of the file.
 * 
 * This file also contains excerpts from Skeletal code distributed in class.
 * 
 ************************************************************************************/
package lk.apiit.nibras.ise;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.KeyStroke;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

public class NIMP
{
	
	private JFrame				mainWindow;
	private JDesktopPane		desktopPane;
	
	private JMenuBar			menuBar;
	private JMenu				mnFile;
	private JMenuItem			mntmOpen;
	private StatusBar			statusBar;
	
	private static NIMP			window;
	
	// Following code snippet was extracted from
	// Claude C. Chibelushi's code samples distributed
	// in class by Mr. Udesh Amarasinghe.
	// (Chibelushi 2009)
	JFileChooser				fileChooser	= new JFileChooser();
	// End of snippet.
	
	private JMenu				mnEnhanceImage;
	private JMenu				mnSmooth;
	
	private JMenu				mnSharpen;
	private JMenu				mnEffects;
	private JMenuItem			mntmNegate;
	private JMenu				mnTransform;
	private JMenuItem			mntmTranslate;
	private JMenuItem			mntmCrop;
	private JMenuItem			mntmScale;
	private JMenuItem			mntmRotate;
	private JMenuItem			mntmAveraging;
	private JMenuItem			mntmSobel;
	private JMenu				mnWeighted;
	private JMenuItem			mntmGaussian;
	private JMenuItem			mntmGaussian_1;
	private JMenu				mnMedian;
	private JMenuItem			mntmMedian;
	private JMenuItem			mntmMin;
	private JMenu				mnLaplacean;
	private JMenuItem			mntmDarkEdges;
	private JMenuItem			mntmLightEdges;
	private JMenuItem			mntmMax;
	private JMenuItem			mntmUnsharpMasking;
	private JMenuItem			mntmExit;
	private JMenuItem			mntmSave;
	private JMenuItem			mntmSaveAs;
	private JSeparator			separator;
	private JSeparator			separator_1;
	private Map<String, String>	fileFormats;
	private JSeparator			separator_2;
	private JMenuItem			mntmAdjustBrightness;
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args)
	{
		// Show the about window.
		// final to allow disposing from the AWTQueue.
		final JFrame about = new AboutWindow();
		about.setVisible(true);
		about.repaint();
		
		EventQueue.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				try
				{
					
					NIMP.getInstance(); // This class is a singleton.
										// Intitialize if not done already.
					
					NIMP.getInstance().openSpecialTaskFile(); // Open the
																// special task
																// file for
																// convenience.
					about.dispose(); // Once program is loaded, remove the about
										// window.
					
				}
				catch (final OutOfMemoryError e)
				{
					// Scaling to large sizes or rotating large images or using
					// a small heap can cause this.
					NIMP.getInstance().showError("Ops! We are out of memory!");
				}
				catch (final Exception e)
				{
					e.printStackTrace();
				}
			}
		});
	}
	
	/**
	 * Create the application.
	 * 
	 * @wbp.parser.entryPoint
	 */
	public NIMP()
	{
		initialize();
	}
	
	private void initialize()
	{
		
		mainWindow = new JFrame();
		this.mainWindow
				.setTitle("NIMP - Nibras's Image Manipulation Program (CB004641)");
		mainWindow.addWindowListener(new WindowAdapter()
		{
			@Override
			public void windowClosing(WindowEvent arg0)
			{
				handleExit();
			}
		});
		
		// Following code snippet was extracted from
		// Claude C. Chibelushi's code samples distributed
		// in class by Mr. Udesh Amarasinghe.
		// (Chibelushi 2009)
		
		final Dimension screenSize = mainWindow.getToolkit().getScreenSize();
		mainWindow.setBounds(0, 0, screenSize.width, screenSize.height - 50);
		
		// End of snippet.
		
		// Code written by me/author.
		
		statusBar = new StatusBar();
		
		mainWindow.getContentPane().add(statusBar, BorderLayout.SOUTH);
		
		// (JavaDocs n.d.)
		final FileFilter filter = new FileNameExtensionFilter(
				"Supported Files", ImageIO.getReaderFileSuffixes());
		
		final String[] formats = ImageIO.getReaderFileSuffixes();
		
		fileFormats = new HashMap<String, String>();
		
		fileChooser.setAcceptAllFileFilterUsed(true);
		
		fileChooser.setFileFilter(filter);
		
		for (final String s : formats)
		{
			fileFormats.put(s + " files", s);
			
			final FileFilter temp = new FileNameExtensionFilter(s + " files", s);
			fileChooser.addChoosableFileFilter(temp);
			
		}
		
		// End of author's code.
		// Anything that follows within this method is generated by Eclipse
		// WindowBuilder.
		
		mainWindow
				.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		
		desktopPane = new JDesktopPane();
		mainWindow.getContentPane().add(desktopPane, BorderLayout.CENTER);
		
		menuBar = new JMenuBar();
		mainWindow.setJMenuBar(menuBar);
		mnFile = new JMenu("File");
		this.mnFile.setMnemonic('F');
		menuBar.add(mnFile);
		mntmOpen = new JMenuItem("Open");
		mntmOpen.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O,
				InputEvent.CTRL_MASK));
		mntmOpen.setMnemonic(KeyEvent.VK_O);
		mntmOpen.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleFileOpen();
			}
			
		});
		mnFile.add(mntmOpen);
		separator_1 = new JSeparator();
		mnFile.add(separator_1);
		mntmSave = new JMenuItem("Save");
		this.mntmSave.setMnemonic(KeyEvent.VK_S);
		mntmSave.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleSave();
			}
		});
		mntmSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S,
				InputEvent.CTRL_MASK));
		mnFile.add(mntmSave);
		mntmSaveAs = new JMenuItem("Save as");
		this.mntmSaveAs.setMnemonic(KeyEvent.VK_A);
		mntmSaveAs.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleSaveAs();
				
			}
		});
		mntmSaveAs.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S,
				InputEvent.CTRL_MASK | InputEvent.SHIFT_MASK));
		mnFile.add(mntmSaveAs);
		this.separator_8 = new JSeparator();
		this.mnFile.add(this.separator_8);
		this.mntmRevert = new JMenuItem("Revert");
		this.mntmRevert.setMnemonic(KeyEvent.VK_R);
		this.mntmRevert.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleRevert();
			}
		});
		this.mnFile.add(this.mntmRevert);
		this.separator_9 = new JSeparator();
		this.mnFile.add(this.separator_9);
		this.mntmClose = new JMenuItem("Close");
		this.mntmClose.setMnemonic(KeyEvent.VK_C);
		this.mntmClose.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleClose();
				;
			}
		});
		this.mnFile.add(this.mntmClose);
		this.mntmCloseAll = new JMenuItem("Close all");
		this.mntmCloseAll.setMnemonic(KeyEvent.VK_L);
		this.mntmCloseAll.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F4,
				InputEvent.ALT_MASK | InputEvent.SHIFT_MASK));
		this.mntmCloseAll.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleCloseAll();
			}
			
		});
		this.mnFile.add(this.mntmCloseAll);
		separator = new JSeparator();
		mnFile.add(separator);
		mntmExit = new JMenuItem("Exit");
		this.mntmExit.setMnemonic(KeyEvent.VK_X);
		mntmExit.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleExit();
			}
		});
		mntmExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F4,
				InputEvent.ALT_MASK));
		mnFile.add(mntmExit);
		mnTransform = new JMenu("Transform");
		this.mnTransform.setMnemonic('T');
		menuBar.add(mnTransform);
		mntmCrop = new JMenuItem("Crop");
		this.mntmCrop.setMnemonic(KeyEvent.VK_C);
		this.mntmCrop.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C,
				InputEvent.CTRL_MASK));
		this.mntmCrop.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleCrop();
			}
		});
		mnTransform.add(mntmCrop);
		mntmTranslate = new JMenuItem("Translate");
		this.mntmTranslate.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_SPACE, InputEvent.CTRL_MASK));
		this.mntmTranslate.setMnemonic(KeyEvent.VK_R);
		mntmTranslate.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleTranslate();
			}
		});
		mnTransform.add(mntmTranslate);
		this.separator_10 = new JSeparator();
		this.mnTransform.add(this.separator_10);
		this.mnScale = new JMenu("Scale");
		this.mnScale.setMnemonic('S');
		this.mnTransform.add(this.mnScale);
		mntmScale = new JMenuItem("Basic");
		this.mntmScale.setMnemonic(KeyEvent.VK_B);
		this.mntmScale.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_PLUS,
				InputEvent.CTRL_MASK | InputEvent.SHIFT_MASK));
		this.mnScale.add(this.mntmScale);
		this.mntmBilinear = new JMenuItem("Bilinear");
		this.mntmBilinear.setMnemonic(KeyEvent.VK_L);
		this.mntmBilinear.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_PLUS, InputEvent.CTRL_MASK | InputEvent.ALT_MASK
						| InputEvent.SHIFT_MASK));
		this.mntmBilinear.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleBilinearScaleImage();
			}
		});
		this.mnScale.add(this.mntmBilinear);
		mntmScale.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleBasicScaleImage();
			}
		});
		this.mnRotate = new JMenu("Rotate");
		this.mnRotate.setMnemonic('R');
		this.mnTransform.add(this.mnRotate);
		mntmRotate = new JMenuItem("Basic");
		this.mntmRotate.setMnemonic(KeyEvent.VK_B);
		this.mntmRotate.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R,
				InputEvent.CTRL_MASK | InputEvent.SHIFT_MASK));
		this.mnRotate.add(this.mntmRotate);
		this.mntmInterpolate = new JMenuItem("Bilinear");
		this.mntmInterpolate.setMnemonic(KeyEvent.VK_L);
		this.mntmInterpolate.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_R, InputEvent.CTRL_MASK | InputEvent.ALT_MASK
						| InputEvent.SHIFT_MASK));
		this.mntmInterpolate.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleRotateInterpolated();
			}
			
		});
		this.mnRotate.add(this.mntmInterpolate);
		mntmRotate.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleRotate();
			}
		});
		separator_3 = new JSeparator();
		mnTransform.add(separator_3);
		mnConvert = new JMenu("Convert");
		this.mnConvert.setMnemonic(KeyEvent.VK_T);
		mnTransform.add(mnConvert);
		mntmConvertToBw = new JMenuItem("Black & White");
		this.mntmConvertToBw.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_B, InputEvent.CTRL_MASK));
		this.mntmConvertToBw.setMnemonic(KeyEvent.VK_B);
		mnConvert.add(mntmConvertToBw);
		mntmConvertToBw.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleThresholdToBWat128();
			}
			
		});
		this.mnGrayScale = new JMenu("Gray Scale");
		this.mnGrayScale.setMnemonic(KeyEvent.VK_G);
		this.mnConvert.add(this.mnGrayScale);
		mntmConvertToGray = new JMenuItem("Averaging");
		this.mntmConvertToGray.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_G, InputEvent.CTRL_MASK));
		this.mntmConvertToGray.setMnemonic(KeyEvent.VK_A);
		this.mnGrayScale.add(this.mntmConvertToGray);
		this.mntmLuminescence = new JMenuItem("Luminescence");
		this.mntmLuminescence.setMnemonic(KeyEvent.VK_L);
		this.mntmLuminescence.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleConvertToGrayScaleUsingLum();
			}
			
		});
		this.mnGrayScale.add(this.mntmLuminescence);
		mntmConvertToGray.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleConvertToGrayScaleUsingAvg();
			}
		});
		mnEnhanceImage = new JMenu("Enhance");
		this.mnEnhanceImage.setMnemonic('N');
		menuBar.add(mnEnhanceImage);
		mnSmooth = new JMenu("Smoothen");
		this.mnSmooth.setMnemonic('m');
		mnEnhanceImage.add(mnSmooth);
		mnWeighted = new JMenu("Weighted");
		this.mnWeighted.setMnemonic(KeyEvent.VK_W);
		mnSmooth.add(mnWeighted);
		mntmAveraging = new JMenuItem("Averaging");
		this.mntmAveraging.setMnemonic(KeyEvent.VK_A);
		mnWeighted.add(mntmAveraging);
		mntmGaussian = new JMenuItem("Gaussian 1");
		this.mntmGaussian.setMnemonic(KeyEvent.VK_G);
		mntmGaussian.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleGaussian1Filter();
			}
		});
		mntmKvalue = new JMenuItem("K-Value");
		this.mntmKvalue.setMnemonic(KeyEvent.VK_K);
		mnWeighted.add(mntmKvalue);
		mntmKvalue.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleKValueFilter();
			}
		});
		this.separator_14 = new JSeparator();
		this.mnWeighted.add(this.separator_14);
		mnWeighted.add(mntmGaussian);
		mntmGaussian_1 = new JMenuItem("Gaussian 2");
		this.mntmGaussian_1.setMnemonic(KeyEvent.VK_2);
		mntmGaussian_1.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleGaussian2Filter();
			}
		});
		mnWeighted.add(mntmGaussian_1);
		mnMedian = new JMenu("Median");
		this.mnMedian.setMnemonic('M');
		mnSmooth.add(mnMedian);
		mntmMedian = new JMenuItem("Median");
		this.mntmMedian.setMnemonic(KeyEvent.VK_M);
		mntmMedian.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleMedianFilter();
			}
		});
		mnMedian.add(mntmMedian);
		mntmMin = new JMenuItem("Min");
		this.mntmMin.setMnemonic(KeyEvent.VK_N);
		mntmMin.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleMedianLowFilter();
			}
		});
		mnMedian.add(mntmMin);
		mntmMax = new JMenuItem("Max");
		this.mntmMax.setMnemonic(KeyEvent.VK_X);
		mntmMax.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleMedianHighFilter();
			}
		});
		mnMedian.add(mntmMax);
		mntmMode = new JMenuItem("Mode");
		this.mntmMode.setMnemonic(KeyEvent.VK_O);
		mntmMode.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleModelFilter();
			}
		});
		mnSmooth.add(mntmMode);
		mntmAveraging.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleAverageFilter();
			}
		});
		mnSharpen = new JMenu("Sharpen");
		this.mnSharpen.setMnemonic('h');
		mnEnhanceImage.add(mnSharpen);
		mntmUnsharpMasking = new JMenuItem("Unsharp Masking");
		this.mntmUnsharpMasking.setMnemonic(KeyEvent.VK_U);
		mntmUnsharpMasking.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleUnsharpMasking();
			}
		});
		mnSharpen.add(mntmUnsharpMasking);
		mntmSobel = new JMenuItem("Sobel");
		this.mntmSobel.setMnemonic(KeyEvent.VK_S);
		this.mnSharpen.add(this.mntmSobel);
		mntmSobel.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleSobelOperator();
			}
		});
		mnLaplacean = new JMenu("Laplacean");
		this.mnLaplacean.setMnemonic(KeyEvent.VK_L);
		this.mnSharpen.add(this.mnLaplacean);
		mntmDarkEdges = new JMenuItem("Dark Edges");
		this.mntmDarkEdges.setMnemonic(KeyEvent.VK_D);
		mntmDarkEdges.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleLaplaceanDarkFilter();
			}
		});
		mnLaplacean.add(mntmDarkEdges);
		mntmLightEdges = new JMenuItem("Light Edges");
		this.mntmLightEdges.setMnemonic(KeyEvent.VK_L);
		mntmLightEdges.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleLaplaceanLightFilter();
			}
		});
		mnLaplacean.add(mntmLightEdges);
		separator_2 = new JSeparator();
		mnEnhanceImage.add(separator_2);
		mntmAdjustBrightness = new JMenuItem("Adjust Brightness");
		this.mntmAdjustBrightness.setMnemonic(KeyEvent.VK_B);
		mntmAdjustBrightness.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleBrightnessAdjust();
			}
		});
		mnEnhanceImage.add(mntmAdjustBrightness);
		mnImproveContrast = new JMenu("Adjust Contrast");
		this.mnImproveContrast.setMnemonic(KeyEvent.VK_C);
		mnEnhanceImage.add(mnImproveContrast);
		mntmNaively = new JMenuItem("Naively");
		this.mntmNaively.setMnemonic(KeyEvent.VK_N);
		mntmNaively.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleNaiveContrastEnhancement();
			}
		});
		mnImproveContrast.add(mntmNaively);
		mnHistogram = new JMenu("Histogram");
		this.mnHistogram.setMnemonic('H');
		mnImproveContrast.add(mnHistogram);
		mntmHistogramEqualization = new JMenuItem("Equalization");
		this.mntmHistogramEqualization.setMnemonic(KeyEvent.VK_E);
		mnHistogram.add(mntmHistogramEqualization);
		mntmHistogramEqualization.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleContrastEnhancementByHistogramEqualization();
			}
		});
		separator_4 = new JSeparator();
		mnHistogram.add(separator_4);
		mntmHistrogramStretch = new JMenuItem("Stretch (0-255)");
		this.mntmHistrogramStretch.setMnemonic(KeyEvent.VK_S);
		mnHistogram.add(mntmHistrogramStretch);
		mntmHistrogramStretch.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleHistogramStretchContrastEnhancement();
			}
			
		});
		mntmHistogramStretchcustom = new JMenuItem("Stretch (Custom)");
		this.mntmHistogramStretchcustom.setMnemonic(KeyEvent.VK_C);
		mnHistogram.add(mntmHistogramStretchcustom);
		this.separator_7 = new JSeparator();
		this.mnEnhanceImage.add(this.separator_7);
		this.mntmSegment = new JMenuItem("Segment");
		this.mntmSegment.setMnemonic(KeyEvent.VK_S);
		this.mntmSegment.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleThresholdToBWatOtsu();
			}
		});
		this.mnEnhanceImage.add(this.mntmSegment);
		mntmHistogramStretchcustom.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleHistogramStretchContrastEnhancementCustom();
			}
		});
		mnEffects = new JMenu("Apply Effect");
		this.mnEffects.setMnemonic('E');
		menuBar.add(mnEffects);
		mntmNegate = new JMenuItem("Negate");
		this.mntmNegate.setMnemonic(KeyEvent.VK_N);
		mntmNegate.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleNegate();
			}
			
		});
		mnEffects.add(mntmNegate);
		mntmQuantize = new JMenuItem("Quantize");
		this.mntmQuantize.setMnemonic(KeyEvent.VK_Q);
		mntmQuantize.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handleQuantize();
			}
		});
		mnEffects.add(mntmQuantize);
		this.mnThreshold = new JMenu("Threshold");
		this.mnThreshold.setMnemonic(KeyEvent.VK_T);
		this.mnEffects.add(this.mnThreshold);
		this.mntmAt = new JMenuItem("at 128");
		this.mntmAt.setMnemonic(KeyEvent.VK_1);
		this.mntmAt.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				
				handleThresholdat128();
			}
		});
		this.mnThreshold.add(this.mntmAt);
		this.mntmAuto = new JMenuItem("auto");
		this.mntmAuto.setMnemonic(KeyEvent.VK_A);
		this.mntmAuto.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleThresholdatOtsu();
			}
		});
		this.mnThreshold.add(this.mntmAuto);
		separator_6 = new JSeparator();
		mnEffects.add(separator_6);
		mnEdgeDetection = new JMenu("Edge Detection");
		this.mnEdgeDetection.setMnemonic('E');
		mnEffects.add(mnEdgeDetection);
		mnLaplacean_1 = new JMenu("Laplacean");
		this.mnLaplacean_1.setMnemonic('L');
		mnEdgeDetection.add(mnLaplacean_1);
		mntmDark = new JMenuItem("Dark");
		this.mntmDark.setMnemonic(KeyEvent.VK_D);
		mntmDark.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleDetectEdgesLaplaceanDark();
			}
		});
		mnLaplacean_1.add(mntmDark);
		mntmLight = new JMenuItem("Light");
		this.mntmLight.setMnemonic(KeyEvent.VK_L);
		mntmLight.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleEdgeDetectionLaplaceanLight();
			}
		});
		mnLaplacean_1.add(mntmLight);
		mntmSobel_2 = new JMenuItem("Sobel");
		this.mntmSobel_2.setMnemonic(KeyEvent.VK_S);
		mntmSobel_2.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleEdgeDetectionSobel();
			}
		});
		mnEdgeDetection.add(mntmSobel_2);
		mnPencilSketch = new JMenu("Pencil Sketch");
		this.mnPencilSketch.setMnemonic('P');
		mnEffects.add(mnPencilSketch);
		mntmSobel_1 = new JMenuItem("Sobel");
		this.mntmSobel_1.setMnemonic(KeyEvent.VK_S);
		mntmSobel_1.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleSobelPencilSketch();
			}
		});
		mnPencilSketch.add(mntmSobel_1);
		this.mntmJinZhou = new JMenuItem("Jin Zhou");
		this.mntmJinZhou.setMnemonic(KeyEvent.VK_J);
		this.mntmJinZhou.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleJinZhouPencilSketch();
			}
		});
		this.mnPencilSketch.add(this.mntmJinZhou);
		mnLaplacean_2 = new JMenu("Laplacean");
		this.mnLaplacean_2.setMnemonic(KeyEvent.VK_L);
		mnPencilSketch.add(mnLaplacean_2);
		mntmDark_1 = new JMenuItem("Dark");
		this.mntmDark_1.setMnemonic(KeyEvent.VK_D);
		mntmDark_1.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleLaplaceanDarkPencilSketch();
			}
		});
		mnLaplacean_2.add(mntmDark_1);
		mntmLight_1 = new JMenuItem("Light");
		this.mntmLight_1.setMnemonic(KeyEvent.VK_L);
		mntmLight_1.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				handleLaplaceanLightPencilSketch();
			}
		});
		mnLaplacean_2.add(mntmLight_1);
		separator_5 = new JSeparator();
		mnEffects.add(separator_5);
		this.mntmFade = new JMenuItem("Fade");
		this.mntmFade.setMnemonic(KeyEvent.VK_F);
		this.mntmFade.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleFade();
			}
		});
		mntmPixellate = new JMenuItem("Pixellate");
		this.mntmPixellate.setMnemonic(KeyEvent.VK_X);
		mntmPixellate.addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent arg0)
			{
				handlePixellate();
			}
		});
		mnEffects.add(mntmPixellate);
		this.separator_12 = new JSeparator();
		this.mnEffects.add(this.separator_12);
		this.mnEffects.add(this.mntmFade);
		this.separator_13 = new JSeparator();
		this.mnEffects.add(this.separator_13);
		this.mnWarp = new JMenu("Warp");
		this.mnWarp.setMnemonic(KeyEvent.VK_W);
		this.mnEffects.add(this.mnWarp);
		this.mntmBulge = new JMenuItem("Fish Eye");
		this.mntmBulge.setMnemonic(KeyEvent.VK_F);
		this.mntmBulge.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleWarpFishEye();
			}
			
		});
		this.mnWarp.add(this.mntmBulge);
		this.mntmBulge_1 = new JMenuItem("Bulge");
		this.mntmBulge_1.setMnemonic(KeyEvent.VK_B);
		this.mntmBulge_1.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleBulgeEye();
			}
		});
		this.mnWarp.add(this.mntmBulge_1);
		this.mntmTwirl = new JMenuItem("Twirl");
		this.mntmTwirl.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent arg0)
			{
				handleTwirlWarp();
			}
		});
		this.mntmTwirl.setMnemonic(KeyEvent.VK_T);
		this.mnWarp.add(this.mntmTwirl);
		this.mnHelp = new JMenu("Help");
		this.mnHelp.setMnemonic(KeyEvent.VK_H);
		this.menuBar.add(this.mnHelp);
		this.mntmUserGuide = new JMenuItem("View Guide");
		this.mntmUserGuide.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleShowDoc();
			}
		});
		this.mntmUserGuide.setAccelerator(KeyStroke.getKeyStroke(
				KeyEvent.VK_F1, 0));
		this.mntmUserGuide.setMnemonic(KeyEvent.VK_G);
		this.mnHelp.add(this.mntmUserGuide);
		this.mntmViewDemo = new JMenuItem("View Demo");
		this.mntmViewDemo.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleShowDemo();
				
			}
		});
		this.mntmViewDemo.setMnemonic(KeyEvent.VK_D);
		this.mnHelp.add(this.mntmViewDemo);
		this.separator_11 = new JSeparator();
		this.mnHelp.add(this.separator_11);
		this.mntmAboutNimp = new JMenuItem("About NIMP");
		this.mntmAboutNimp.addActionListener(new ActionListener()
		{
			public void actionPerformed(ActionEvent e)
			{
				handleShowAbout();
				
			}
		});
		this.mntmAboutNimp.setMnemonic(KeyEvent.VK_A);
		this.mnHelp.add(this.mntmAboutNimp);
		
		mainWindow.setVisible(true);
		
	}
	
	public void handleShowAbout()
	{
		new AboutWindow();
		
	}
	
	public void handleShowDemo()
	{
		try
		{
			Desktop.getDesktop().open(new File("demo.pdf"));
		}
		catch (IOException e)
		{
			showError("Error opening file! Do you have a PDF viewer?");
		}
		
	}
	
	public void handleShowDoc()
	{
		try
		{
			Desktop.getDesktop().open(new File("guide.pdf"));
		}
		catch (IOException e)
		{
			showError("Error opening file! Do you have a PDF viewer?");
		}
		
	}
	
	public void handleWarpFishEye()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(500, 15);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.applyFishEyeWarp(value / 100.0);
			}
		});
		
		//
		//
		final int resp = JOptionPane
				.showInternalConfirmDialog(active, new Object[] {
						"Select the focal length of the lense (cm)\n", slide },
						"Apply Fish Eye", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleBulgeEye()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(100, 10);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.applyBulgeWarp(value / 10.0);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the factor of effect", slide },
				"Apply Bulge", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleTwirlWarp()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(100, 1);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.applyTwirlWarp(value / 100.0);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the factor of effect", slide },
				"Apply Twirl", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleClose()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No window to close!");
			return;
		}
		
		// (stackoverflow 2010)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		
		try
		{
			active.setClosed(true);
		}
		catch (final PropertyVetoException e)
		{
			showError("Error closing window!");
		}
		
	}
	
	public void handleCloseAll()
	{
		
		// (stackoverflow 2010)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (stackoverflow 2010)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		// (JavaDocs n.d.)
		//
		
		JInternalFrame[] frames = desktopPane.getAllFrames();
		
		while (frames.length != 0)
		{
			for (final JInternalFrame frame : frames)
				try
				{
					frame.setClosed(true);
				}
				catch (final PropertyVetoException e)
				{
					showError("Error closing window: " + frame.getTitle() + "!");
				}
			
			frames = desktopPane.getAllFrames();
		}
		
	}
	
	public void handleRevert()
	{
		statusBar.setStatus("Revert Opening file...");
		
		// (The Java Tutorials n.d.)
		
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		if (!active.isSaved())
			if (JOptionPane
					.showConfirmDialog(
							active,
							"Are you sure you want load this file again from disk? All unsaved changes will be lost!",
							"Confirm Revert", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION)
			{
				getStatusBar().setStatus("");
				return;
			}
		
		BufferedImage image;
		File file;
		try
		{
			// (stackoverflow n.d.)
			
			file = new File(active.getTitle());
			final String name = active.getTitle();
			if (name.substring(name.lastIndexOf('.') + 1, name.length())
					.equals("raw"))
				image = readRaw(file);
			else
				image = ImageIO.read(file);
		}
		catch (final IOException e)
		{
			showError("An error occured while opening file!");
			return;
		}
		
		if (image == null)
		{
			showError("Unsupported file format!");
			return;
		}
		
		active.setImage(image);
		
		statusBar.setStatus("");
		
	}
	
	public void handleCrop()
	{
		ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		JOptionPane
				.showInternalMessageDialog(
						active,
						"Please click select the area to be cropped. Start from top-right and move towards bottom-left.");
		
		active.handleCrop();
		
	}
	
	public void handleModelFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyModeFilter();
	}
	
	public void handleNaiveContrastEnhancement()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(255, 1);
		slide.setValue(0);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.applyContrastEnhancementNaively(value);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] {
						"Select the scale by which to increase contrast:\n",
						slide }, "Adjust Contrast",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleContrastEnhancementByHistogramEqualization()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.applyContrastEnhancementByEqualization();
		
	}
	
	public void handleHistogramStretchContrastEnhancement()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.applyContrastEnhancementByStretching();
		
	}
	
	int	maxCont, minCont;
	
	public void handleHistogramStretchContrastEnhancementCustom()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to improve contrast!");
			return;
		}
		
		active.prepUndo();
		final JSlider max = getSlider(255, 0);
		final JSlider min = getSlider(255, 0);
		
		max.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				maxCont = ((JSlider) arg0.getSource()).getValue();
				
				active.applyContrastEnhancementByStretching(maxCont, minCont);
				
				if (keepToScale && min.getValue() != 255 - maxCont)
					min.setValue(255 - maxCont);
				
			}
		});
		
		min.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				minCont = ((JSlider) arg0.getSource()).getValue();
				
				active.applyContrastEnhancementByStretching(maxCont, minCont);
				
				if (keepToScale && max.getValue() != 255 - minCont)
					max.setValue(255 - minCont);
				
			}
		});
		
		final JCheckBox chk = getKeepToScaleCheckBox();
		chk.setText("Equivalent");
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] {
						"Select the scale by which to increase contrast:\n\n",
						"Maximum", max, "\nMinimum", min, chk },
				"Adjust Contrast", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleThresholdToBWat128()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyThresholdToBW128();
		
	}
	
	public void handleThresholdToBWatOtsu()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyThresholdToBWOtsu();
		
	}
	
	public void handleThresholdatOtsu()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyThresholdOtsu();
		;
		
	}
	
	public void handleThresholdat128()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyThreshold128();
		;
		
	}
	
	public void handleConvertToGrayScaleUsingAvg()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyConvertToGrayScaleUsingAvg();
		
	}
	
	public void handleConvertToGrayScaleUsingLum()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		active.applyConvertToGrayScaleUsingLum();
		
	}
	
	public void handleFade()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to fade!");
			return;
		}
		
		if (desktopPane.getAllFrames().length < 2)
		{
			showError("You need another image to use as a target");
			return;
		}
		
		final JComboBox<ImageWindow> images = new JComboBox<ImageWindow>();
		
		if (desktopPane.getAllFrames().length < 2)
			showError("You need another image to use as a target");
		for (JInternalFrame frame : desktopPane.getAllFrames())
			images.addItem((ImageWindow) frame);
		
		if (JOptionPane.showConfirmDialog(active, images,
				"Select second images: ", JOptionPane.OK_CANCEL_OPTION) != JOptionPane.OK_OPTION)
			return;
		
		final JSlider slide = getSlider(100, 0);
		
		active.prepUndo();
		
		slide.addChangeListener(new ChangeListener()
		{
			
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				active.applyFading(slide.getValue() / 100.0,
						(ImageWindow) images.getSelectedItem());
				
			}
		});
		if (JOptionPane.showConfirmDialog(active, slide,
				"Percentage to fade: ", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.CANCEL_OPTION)
			active.undo();
		
	}
	
	public void handleQuantize()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to quantize!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(128, 2);
		slide.setValue(0);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.quantizeImage((short) value);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane
				.showInternalConfirmDialog(
						active,
						new Object[] {
								"Select the step size to use when quantizing:\n",
								slide }, "Bunching",
						JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleEdgeDetectionSobel()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		
		active.applySobelMaskOnly();
		
	}
	
	public void handleEdgeDetectionLaplaceanLight()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		
		active.applyLapleanLightMaskOnly();
		
	}
	
	public void handleDetectEdgesLaplaceanDark()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		
		active.applyLapleanDarkMaskOnly();
	}
	
	public void handleLaplaceanLightPencilSketch()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		final JSlider slide = getSlider(255, 1);
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select color of the lightest pencil shade:\n",
						slide }, "Create Pencil Sketch",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp == JOptionPane.OK_OPTION)
			active.applyPencilSketchUsingLaplaceanLight((short) slide
					.getValue());
		
	}
	
	public void handleLaplaceanDarkPencilSketch()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		final JSlider slide = getSlider(255, 1);
		
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select color of the lightest pencil shade:\n",
						slide }, "Create Pencil Sketch",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp == JOptionPane.OK_OPTION)
			active.applyPencilSketchUsingLaplaceanDark((short) slide.getValue());
		
	}
	
	public void handleJinZhouPencilSketch()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		final JSlider slide = getSlider(255, 1);
		
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select color of the lightest pencil shade:\n",
						slide }, "Create Pencil Sketch",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp == JOptionPane.OK_OPTION)
			active.applyPencilSketchUsingJinZhou((short) slide.getValue());
		
	}
	
	public void handleSobelPencilSketch()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to modify!");
			return;
		}
		
		final JSlider slide = getSlider(255, 1);
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select color of the lightest pencil shade:\n",
						slide }, "Create Pencil Sketch",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp == JOptionPane.OK_OPTION)
			active.applyPencilSketchUsingSobel((short) slide.getValue());
		
	}
	
	public void handleRotate()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to rotate!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(180, -180);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.rotate(value);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the angle by which to rotate image:\n",
						slide }, "Degrees to rotate:",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleRotateInterpolated()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to rotate!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(180, -180);
		slide.setValue(0);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.rotateByInterpolate(value);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the angle by which to rotate image:\n",
						slide }, "Degrees to rotate:",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleBrightnessAdjust()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		
		active.prepUndo();
		final JSlider slide = getSlider(128, -128);
		slide.setValue(0);
		
		slide.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int value = ((JSlider) arg0.getSource()).getValue();
				
				active.adjustBrightness((short) value);
			}
		});
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] {
						"Select the amount by which to adjust brightness:\n",
						slide }, "Adjust Brightness",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleKValueFilter()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		
		int max = active.getImage().getHeight();
		
		if (active.getImage().getWidth() > max)
			max = active.getImage().getWidth();
		
		final JSlider slide = getSlider(max / 10, 1);
		
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the K value:\n", slide },
				"Apply K value filter", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp == JOptionPane.OK_OPTION)
			active.applyKValueFilter(slide.getValue());
	}
	
	// int tempPixellateColSize = 1;
	private JMenuItem	mntmPixellate;
	
	boolean				keepToScale;
	private JMenu		mnPencilSketch;
	private JMenuItem	mntmSobel_1;
	private JMenu		mnEdgeDetection;
	private JMenu		mnLaplacean_1;
	private JMenuItem	mntmDark;
	private JMenuItem	mntmLight;
	private JMenuItem	mntmSobel_2;
	private JMenu		mnLaplacean_2;
	private JMenuItem	mntmDark_1;
	private JMenuItem	mntmLight_1;
	private JMenuItem	mntmQuantize;
	private JMenuItem	mntmConvertToBw;
	private JMenuItem	mntmConvertToGray;
	private JSeparator	separator_3;
	
	private JMenu		mnImproveContrast;
	private JMenuItem	mntmNaively;
	private JMenuItem	mntmHistrogramStretch;
	private JMenuItem	mntmHistogramStretchcustom;
	private JMenuItem	mntmHistogramEqualization;
	private JMenuItem	mntmMode;
	private JMenuItem	mntmKvalue;
	private JMenu		mnConvert;
	private JMenu		mnHistogram;
	private JSeparator	separator_4;
	private JSeparator	separator_5;
	private JSeparator	separator_6;
	private JMenu		mnScale;
	private JMenuItem	mntmBilinear;
	private JMenu		mnRotate;
	private JMenuItem	mntmInterpolate;
	private JMenuItem	mntmJinZhou;
	private JMenuItem	mntmSegment;
	private JSeparator	separator_7;
	private JMenu		mnThreshold;
	private JMenuItem	mntmAt;
	private JMenuItem	mntmAuto;
	private JMenuItem	mntmClose;
	private JMenuItem	mntmCloseAll;
	private JMenuItem	mntmRevert;
	private JSeparator	separator_8;
	private JSeparator	separator_9;
	private JMenu		mnGrayScale;
	private JMenuItem	mntmLuminescence;
	private JMenuItem	mntmFade;
	private JMenu		mnWarp;
	private JMenuItem	mntmBulge;
	private JMenuItem	mntmBulge_1;
	private JSeparator	separator_10;
	private JMenu		mnHelp;
	private JMenuItem	mntmUserGuide;
	private JMenuItem	mntmAboutNimp;
	private JSeparator	separator_11;
	private JMenuItem	mntmViewDemo;
	private JSeparator	separator_12;
	private JSeparator	separator_13;
	private JSeparator	separator_14;
	private JMenuItem	mntmTwirl;
	
	public void handlePixellate()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to pixellate!");
			return;
		}
		
		active.prepUndo();
		final JSlider height = getSlider(320, 2);
		final JSlider width = getSlider(320, 2);
		
		height.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int tempPixellateRowSize = ((JSlider) arg0.getSource())
						.getValue();
				
				if (keepToScale && width.getValue() != tempPixellateRowSize)
					width.setValue(tempPixellateRowSize);
				
				active.pixellateImage(tempPixellateRowSize, width.getValue());
				
			}
		});
		
		width.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int tempPixellateColSize = ((JSlider) arg0.getSource())
						.getValue();
				
				if (keepToScale && height.getValue() != tempPixellateColSize)
					height.setValue(tempPixellateColSize);
				
				active.pixellateImage(height.getValue(), tempPixellateColSize);
				
			}
		});
		
		final JCheckBox scale = getKeepToScaleCheckBox();
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the size of a pixel box:\n",
						"Row Size: ", height, "Column Size: ", width, scale },
				"Pixellate", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	public void handleTranslate()
	{
		// (java2s 2009)
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to translate!");
			return;
		}
		
		active.prepUndo();
		
		final int maxV = active.getImage().getHeight();
		final int maxH = active.getImage().getHeight();
		
		final JSlider vertical = getSlider(maxV, -maxV);
		final JSlider horizontal = getSlider(maxH, -maxH);
		
		vertical.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int tempTranslateVertical = ((JSlider) arg0.getSource())
						.getValue();
				
				if (keepToScale
						&& horizontal.getValue() != tempTranslateVertical)
					horizontal.setValue(tempTranslateVertical);
				
				active.applyTranslate(tempTranslateVertical,
						horizontal.getValue());
				
			}
		});
		
		horizontal.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				active.undo();
				
				final int tempTranslateHorizontal = ((JSlider) arg0.getSource())
						.getValue();
				
				if (keepToScale
						&& vertical.getValue() != tempTranslateHorizontal)
					vertical.setValue(tempTranslateHorizontal);
				
				active.applyTranslate(vertical.getValue(),
						tempTranslateHorizontal);
			}
		});
		
		final JCheckBox scale = getKeepToScaleCheckBox();
		//
		// (javadocs n.d.)
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select the number of pixels to move:\n",
						"Vertical Displacement: ", vertical,
						"Horizontal Displacement: ", horizontal, scale },
				"Translate", JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			active.undo();
	}
	
	private JCheckBox getKeepToScaleCheckBox()
	{
		final JCheckBox scale = new JCheckBox("Keep to scale");
		
		scale.setSelected(keepToScale);
		
		scale.addChangeListener(new ChangeListener()
		{
			
			@Override
			public void stateChanged(ChangeEvent arg0)
			{
				keepToScale = ((JCheckBox) arg0.getSource()).isSelected();
				
			}
		});
		return scale;
	}
	
	public void handleSaveAs()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to save!");
			return;
		}
		
		final BufferedImage image = active.getImage();
		
		final int resp = fileChooser.showSaveDialog(mainWindow);
		
		if (resp != JFileChooser.APPROVE_OPTION)
			return;
		
		String absolutePath = fileChooser.getSelectedFile().getAbsolutePath();
		
		String extension = fileFormats.get(fileChooser.getFileFilter()
				.getDescription());
		
		final boolean validExtensionChoosen = extension != null;
		
		final int dotPoint = absolutePath.lastIndexOf('.');
		
		if (!validExtensionChoosen && dotPoint != -1)
			extension = absolutePath.substring(dotPoint + 1,
					absolutePath.length());
		else if (extension == null)
		{
			showError("File must have a valid extension!");
			return;
		}
		
		if (validExtensionChoosen)
		{
			absolutePath = absolutePath + "." + extension;
		}
		
		try
		{
			saveToFile(image, absolutePath, extension);
		}
		catch (final IOException e)
		{
			showError("An error occured while saving the file!");
			handleSaveAs();
		}
		
		active.setTitle(absolutePath);
		active.setSaved(true);
	}
	
	public void handleSave()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to save!");
			return;
		}
		
		final BufferedImage image = active.getImage();
		
		final int resp = JOptionPane.showConfirmDialog(mainWindow,
				"Are you sure you want to save changes to this file?",
				"Confirm Save", JOptionPane.YES_NO_OPTION);
		
		if (resp == JOptionPane.NO_OPTION)
			return;
		
		final String absolutePath = active.getTitle();
		
		final String extension = absolutePath.substring(
				absolutePath.lastIndexOf('.') + 1, absolutePath.length());
		
		try
		{
			
			saveToFile(image, absolutePath, extension);
		}
		catch (final IOException e)
		{
			showError("An error occured while saving the file!");
			handleSave();
		}
		
		active.setSaved(true);
		
	}
	
	private void saveToFile(BufferedImage image, String absolutePath,
			String extension) throws IOException
	{
		final File file = new File(absolutePath);
		
		if (extension.equals("raw"))
			writeRaw(image, file);
		else
			ImageIO.write(image, extension, file);
	}
	
	public void handleExit()
	{
		final int resp = JOptionPane.showConfirmDialog(mainWindow,
				"Are you sure you want to exit?", "Confirm Exit",
				JOptionPane.YES_NO_OPTION);
		
		if (resp == JOptionPane.NO_OPTION)
			return;
		
		// (stackoverflow 2010)
		// (JavaDocs n.d.)
		
		JInternalFrame[] frames = desktopPane.getAllFrames();
		
		while (frames.length != 0)
		{
			for (final JInternalFrame frame : frames)
				try
				{
					frame.setClosed(true);
				}
				catch (final PropertyVetoException e)
				{
					showError("Error closing application!");
				}
			
			frames = desktopPane.getAllFrames();
		}
		
		mainWindow.dispose();
		
	}
	
	// (java2s 2009)
	
	public void handleBasicScaleImage()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to enlarge!");
			return;
		}
		
		final JCheckBox scale = getKeepToScaleCheckBox();
		final JSlider v = getSlider(5, 1);
		final JSlider h = getSlider(5, 1);
		
		v.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent e)
			{
				if (keepToScale && h.getValue() != v.getValue())
					h.setValue(v.getValue());
			}
		});
		
		h.addChangeListener(new ChangeListener()
		{
			
			@Override
			public void stateChanged(ChangeEvent e)
			{
				if (keepToScale && v.getValue() != h.getValue())
					v.setValue(h.getValue());
			}
			
		});
		
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select scaling to use when scaling image!\n",
						"Horizontal", h, "Vertical", v, scale }, "Scaling",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			return;
		
		active.basicEnlarge(h.getValue(), v.getValue());
		
	}
	
	// (java2s 2009)
	
	public void handleBilinearScaleImage()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to enlarge!");
			return;
		}
		
		final JCheckBox scale = getKeepToScaleCheckBox();
		final JSlider v = getSlider(5, 1);
		final JSlider h = getSlider(5, 1);
		
		v.addChangeListener(new ChangeListener()
		{
			@Override
			public void stateChanged(ChangeEvent e)
			{
				if (keepToScale && h.getValue() != v.getValue())
					h.setValue(v.getValue());
			}
		});
		
		h.addChangeListener(new ChangeListener()
		{
			
			@Override
			public void stateChanged(ChangeEvent e)
			{
				if (keepToScale && v.getValue() != h.getValue())
					v.setValue(h.getValue());
			}
			
		});
		
		final int resp = JOptionPane.showInternalConfirmDialog(active,
				new Object[] { "Select scaling to use when scaling image!\n",
						"Horizontal", h, "Vertical", v, scale }, "Scaling",
				JOptionPane.OK_CANCEL_OPTION);
		
		if (resp != JOptionPane.OK_OPTION)
			return;
		
		active.biLinearEnlarge(h.getValue(), v.getValue());
		
	}
	
	private JSlider getSlider(int max, int min)
	{
		final JSlider h = new JSlider();
		h.setMaximum(max);
		h.setMinimum(min);
		h.setMajorTickSpacing((max - min) / 4);
		h.setMinorTickSpacing(1);
		h.setPaintTicks(true);
		h.setPaintTicks(true);
		h.setPaintLabels(true);
		return h;
	}
	
	public void handleSobelOperator()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to highlight edges!");
			return;
		}
		active.applySobelOperator();
		
	}
	
	public void handleUnsharpMasking()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyUnsharpMasking();
	}
	
	public void handleMedianFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyMedianFilter();
		
	}
	
	public void handleMedianLowFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyMedianLowFilter();
		
	}
	
	public void handleMedianHighFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyMedianHighFilter();
		
	}
	
	public void handleLaplaceanLightFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to sharpen edges!");
			return;
		}
		active.applyLaplaceanLightFilter();
		
	}
	
	public void handleLaplaceanDarkFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to sharpen edges!");
			return;
		}
		active.applyLaplaceanDarkFilter();
		
	}
	
	public void handleGaussian1Filter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyGaussian1Filter();
		
	}
	
	public void handleGaussian2Filter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyGaussian2Filter();
		
	}
	
	public void handleAverageFilter()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to smoothen!");
			return;
		}
		active.applyAverageFilter();
	}
	
	private void handleNegate()
	{
		final ImageWindow active = (ImageWindow) desktopPane.getSelectedFrame();
		
		if (active == null)
		{
			showError("No image to negate!");
			return;
		}
		active.negate();
		
	}
	
	/**
	 * @wbp.parser.entryPoint
	 */
	public static NIMP getInstance()
	{
		if (NIMP.window == null)
			NIMP.window = new NIMP();
		return NIMP.window;
		
	}
	
	public StatusBar getStatusBar()
	{
		
		return statusBar;
	}
	
	private void handleFileOpen()
	{ // Following code snippet was derived using
		// Claude C. Chibelushi's code samples distributed
		// in class by Mr. Udesh Amarasinghe.
		// (Chibelushi 2009)
		
		statusBar.setStatus("Opening file...");
		
		// (The Java Tutorials n.d.)
		
		final int resp = fileChooser.showOpenDialog(mainWindow);
		
		if (resp != JFileChooser.APPROVE_OPTION)
		{
			statusBar.setStatus("");
			return;
		}
		
		final int offset = desktopPane.getAllFrames().length * 25;
		final ImageWindow imageFrame = new ImageWindow(offset, offset, 300);
		BufferedImage image;
		File file;
		try
		{
			// (stackoverflow n.d.)
			file = fileChooser.getSelectedFile();
			
			final String name = file.getName();
			if (name.substring(name.lastIndexOf('.') + 1, name.length())
					.equals("raw"))
				image = readRaw(file);
			else
				image = ImageIO.read(file);
		}
		catch (final IOException e)
		{
			showError("An error occured while opening file!");
			return;
		}
		
		if (image == null)
		{
			showError("Unsupported file format!");
			return;
		}
		
		imageFrame.setImage(image);
		
		imageFrame.setTitle(file.getAbsolutePath());
		desktopPane.add(imageFrame);
		imageFrame.setVisible(true);
		statusBar.setStatus("");
		
	}
	
	private BufferedImage readRaw(File file) throws IOException
	{// Following code snippet was derived also using
		// Claude C. Chibelushi's code samples distributed
		// in class by Mr. Udesh Amarasinghe.
		// (Chibelushi 2009)
		final int imHeight = 480;
		final int imWidth = 640;
		int temp;
		
		final BufferedImage image = new BufferedImage(imWidth, imHeight,
				BufferedImage.TYPE_INT_ARGB);
		
		// (stackoverflow 2012)
		// (JavaDocs n.d.)
		
		final DataInputStream inputStream = new DataInputStream(
				new FileInputStream(file));
		
		for (int row = 0; row < imHeight; ++row)
			for (int col = 0; col < imWidth; ++col)
			{
				statusBar.setProgress(row / imHeight);
				temp = inputStream.readUnsignedByte();
				image.setRGB(col, row, 0xFF000000 | temp << 16 | temp << 8
						| temp);
				
			}
		
		inputStream.close();
		
		return image;
		
	}
	
	private void writeRaw(BufferedImage image, File file) throws IOException
	{
		// Following code snippet was extracted from
		// Claude C. Chibelushi's code samples distributed
		// in class by Mr. Udesh Amarasinghe.
		// (Chibelushi 2009)
		
		final int imHeight = 480;
		final int imWidth = 640;
		int temp;
		
		// (stackoverflow 2012)
		// (JavaDocs n.d.)
		
		final DataOutputStream outputStream = new DataOutputStream(
				new FileOutputStream(file));
		
		for (int row = 0; row < imHeight; ++row)
			for (int col = 0; col < imWidth; ++col)
			{
				statusBar.setProgress(row / imHeight);
				
				temp = image.getRGB(col, row);
				outputStream.writeByte(temp >> 16 & 0xff);
				
			}
		
		outputStream.close();
		
	}
	
	public void showError(String message)
	{
		statusBar.setStatus("An error occured!");
		JOptionPane.showMessageDialog(mainWindow, message, "Error",
				JOptionPane.ERROR_MESSAGE);
		statusBar.setStatus("");
	}
	
	private void openSpecialTaskFile()
	{
		// Following code snippet was derived also using
		// Claude C. Chibelushi's code samples distributed
		// in class by Mr. Udesh Amarasinghe.
		// (Chibelushi 2009)
		
		// (The Java Tutorials n.d.)
		
		final ImageWindow imageFrame = new ImageWindow(0, 0, 300);
		BufferedImage image;
		File file;
		try
		{
			// (stackoverflow n.d.)
			file = new File("image.jpg");
			image = ImageIO.read(file);
		}
		catch (final IOException e)
		{
			return;
		}
		
		imageFrame.setImage(image);
		imageFrame.setTitle(file.getAbsolutePath());
		desktopPane.add(imageFrame);
		desktopPane.setSelectedFrame(imageFrame);
		imageFrame.setVisible(true);
		
	}
}

/*************************************************************************************
 * References:
 * 
 * This file also contains excerpts from Skeletal code distributed in class.
 * 
 * Anonymous. n.d. [online] Available at:
 * http://www.apl.jhu.edu/~hall/java/Java2D-Tutorial.html [Accessed: 6 Jan
 * 2014].
 * 
 * Burke, D. 2011. image thumbnail question (Swing / AWT / SWT forum at
 * JavaRanch). [online] Available at:
 * http://www.coderanch.com/t/559661/GUI/java/image-thumbnail [Accessed: 6 Jan
 * 2014].
 * 
 * Campbell, C. 2007. The Perils of Image.getScaledInstance() | Java.net.
 * [online] Available at:
 * https://today.java.net/pub/a/today/2007/04/03/perils-of
 * -image-getscaledinstance.html [Accessed: 6 Jan 2014].
 * 
 * Image, C. 2012. java - Convert short[] into a grayscale image - Stack
 * Overflow. [online] Available at:
 * http://stackoverflow.com/questions/8765004/convert
 * -short-into-a-grayscale-image [Accessed: 7 Jan 2014].
 * 
 * Java, C. 2013. string - Check file extension in Java - Stack Overflow.
 * [online] Available at:
 * http://stackoverflow.com/questions/10928387/check-file-extension-in-java
 * [Accessed: 7 Jan 2014].
 * 
 * Java2s. 2009. Using JOptionPane with a JSlider : JOptionPane Dialog « Swing «
 * Java Tutorial. [online] Available at: http://www.java2s.com/Tutorial/Java/
 * 0240__Swing/UsingJOptionPanewithaJSlider.htm [Accessed: 7 Jan 2014].
 * 
 * javadocs. n.d. JOptionPane (Java Platform SE 7 ). [online] Available at:
 * http://docs.oracle.com/javase/7/docs/api/javax/swing/JOptionPane.html#
 * showInputDialog%28java.awt.Component,%20java.lang.Object%29 [Accessed: 7 Jan
 * 2014].
 * 
 * JavaDocs. n.d. FileNameExtensionFilter (Java Platform SE 6). [online]
 * Available at:
 * http://docs.oracle.com/javase/6/docs/api/javax/swing/filechooser
 * /FileNameExtensionFilter.html [Accessed: 7 Jan 2014].
 * 
 * JavaDocs. n.d. JInternalFrame (Java Platform SE 7 ). [online] Available at:
 * http://docs.oracle.com/javase/7/docs/api/javax/swing/JInternalFrame.html
 * [Accessed: 7 Jan 2014].
 * 
 * JavaDocs. n.d. Component (Java Platform SE 7 ). [online] Available at:
 * http://
 * docs.oracle.com/javase/7/docs/api/java/awt/Component.html#dispatchEvent
 * %28java.awt.AWTEvent%29 [Accessed: 7 Jan 2014].
 * 
 * JavaDocs. n.d. AWTEvent (Java Platform SE 7 ). [online] Available at:
 * http://docs.oracle.com/javase/7/docs/api/java/awt/AWTEvent.html [Accessed: 7
 * Jan 2014].
 * 
 * JavaDocs. n.d. InternalFrameEvent (Java Platform SE 7 ). [online] Available
 * at: http://docs.oracle.com/javase/7/docs/api/javax/swing/event/
 * InternalFrameEvent.html [Accessed: 7 Jan 2014].
 * 
 * JavaDocs. n.d. BufferedImage (Java Platform SE 7 ). [online] Available at:
 * http://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html
 * [Accessed: 7 Jan 2014].
 * 
 * Kaving, J. 2012. swing - Maximizing JInternalFrame in Java - Stack Overflow.
 * [online] Available at:
 * http://stackoverflow.com/questions/9438035/maximizing-jinternalframe-in-java
 * [Accessed: 6 Jan 2014].
 * 
 * stackoverflow. 2014. java - Add a JScrollPane to a JLabel - Stack Overflow.
 * [online] Available at:
 * http://stackoverflow.com/questions/9335138/add-a-jscrollpane-to-a-jlabel
 * [Accessed: 7 Jan 2014].
 * 
 * stackoverflow. 2012. swing - Java ScrollPane on Buffered Image - Stack
 * Overflow. [online] Available at:
 * http://stackoverflow.com/questions/7678840/java-scrollpane-on-buffered-image
 * [Accessed: 7 Jan 2014].
 * 
 * stackoverflow. 2010. java - How to programmatically close a JFrame - Stack
 * Overflow. [online] Available at:
 * http://stackoverflow.com/questions/1234912/how
 * -to-programmatically-close-a-jframe [Accessed: 7 Jan 2014].
 * 
 * The Java Tutorials. n.d. Reading/Loading an Image (The Java™ Tutorials > 2D
 * Graphics > Working with Images). [online] Available at:
 * http://docs.oracle.com/javase/tutorial/2d/images/loadimage.html [Accessed: 7
 * Jan 2014].
 * 
 ************************************************************************************/
